namespaces:
  search-app:
    rules:
      - host: search.calum.run
        paths:
          - path: /
            pathType: Prefix
            serviceName: search-app-frontend
            servicePort: 3000
  argocd:
    rules:
      - host: argocd.calum.run
        paths:
          - path: /
            pathType: Prefix
            serviceName: argocd-server
            servicePort: 80

  portfolio:
    rules:
      - host: about.calum.run
        paths:
          - path: /
            pathType: Prefix
            serviceName: portfolio
            servicePort: 3000
